<button class='btn btn-danger' type="button">обновить данные с расходников</button>
<img src="/img/ajax-loader.gif" style="display:none"/>
<script type="text/javascript">
    $('button').click(function(){
        $('img').show();
        $('button').text('обновление');
        changeBtn('btn-danger','btn-warning');
        $.ajax({
            url:'update',
            type:'HEAD',
            cache:false,
            success:function(){
                changeBtn('btn-warning','btn-success');
                $('button').text('данные обновлены');
                $('img').hide();
            }

        })

    });

    function changeBtn(delClass,pasteClass){
        $('button').removeClass(delClass);
        $('button').addClass(pasteClass);
    }
</script>